/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package field;

/**
 *
 * @author ZZ17390
 */
public class Syaryo {
    //Syaryo
    public enum _Syaryo implements Fields{
	KSYCD("KSYCD"),
	KISY("KISY"),
	KIBAN("KIBAN"),
	TYP("TYP"),
	SYHK("SYHK"),
	SEHN_BNR_CD_A("SEHN_BNR_CD_A"),
	SEHN_BNR_CD_B("SEHN_BNR_CD_B"),
	SEHN_BNR_CD_4("SEHN_BNR_CD_4"),
	SEHN_BNR_CD_5("SEHN_BNR_CD_5"),
	MAKR_KBN("MAKR_KBN"),
	SVC_TS_KBN("SVC_TS_KBN"),
	SYRK_KBN("SYRK_KBN"),
	SYRK_YMD("SYRK_YMD"),
	HY_KKYKCD("HY_KKYKCD"),
	KYSCD("KYSCD"),
	KOMTRAX_OBE_FLG("KOMTRAX_OBE_FLG"),
	KOMTRX_SOTY_KBN("KOMTRX_SOTY_KBN"),
	KOMTRAX_SYB("KOMTRAX_SYB"),
	NNY_YMD("NNY_YMD"),
	KKYK_KNRNO("KKYK_KNRNO"),
	TDB_KRSFLG("TDB_KRSFLG"),
	NU_KBN("NU_KBN"),
	ENJN_TYP_1("ENJN_TYP_1"),
	ENJNNO_1("ENJNNO_1"),
	ENJN_KKDAY_1("ENJN_KKDAY_1"),
	ENJN_TYP_2("ENJN_TYP_2"),
	ENJNNO_2("ENJNNO_2"),
	ENJN_KKDAY_2("ENJN_KKDAY_2"),
	SVC_MTR("SVC_MTR"),
	SVC_MTR_NUPDAY("SVC_MTR_NUPDAY"),
	ODO("ODO"),
	ODO_KNDAY("ODO_KNDAY"),
	SYAR_KEY_SYB("SYAR_KEY_SYB"),
	SSK_ANZN_KJTKG_KBN("SSK_ANZN_KJTKG_KBN"),
	HKGS_HKSI_TKGO_KBN("HKGS_HKSI_TKGO_KBN"),
	GUS_TSDAY("GUS_TSDAY"),
	TSOH_KSEI_TKGO_KBN("TSOH_KSEI_TKGO_KBN"),
	TSDH_KSEI_TKGO_KBN("TSDH_KSEI_TKGO_KBN"),
	SIY_NNRY_KBN("SIY_NNRY_KBN"),
	PINNO("PINNO"),
	CTNT_PNTCD("CTNT_PNTCD"),
	TNT_DR_PNTCD("TNT_DR_PNTCD"),
	SVC_SALE_TNTCD("SVC_SALE_TNTCD"),
	KADO_TIKU_CD("KADO_TIKU_CD"),
	LTGC_KNDAY("LTGC_KNDAY"),
	HOSY_SYOKNO("HOSY_SYOKNO"),
	HJUN_HSKK_MMSU("HJUN_HSKK_MMSU"),
	HJUN_HSTM("HJUN_HSTM"),
	NCHSHO_STDAY("NCHSHO_STDAY"),
	HJUN_HOSY_EDYM("HJUN_HOSY_EDYM"),
	NCTR_TSFLG("NCTR_TSFLG"),
	NCTR_YTDAY_1("NCTR_YTDAY_1"),
	NCTR_JSDAY_1("NCTR_JSDAY_1"),
	NCTR_YTDAY_2("NCTR_YTDAY_2"),
	NCTR_JSDAY_2("NCTR_JSDAY_2"),
	NCTR_YTDAY_3("NCTR_YTDAY_3"),
	NCTR_JSDAY_3("NCTR_JSDAY_3"),
	TB_HOSY_KBN("TB_HOSY_KBN"),
	KM_HOSY_UMFLG("KM_HOSY_UMFLG"),
	SVC_HOSY_UMFLG("SVC_HOSY_UMFLG"),
	SCV_HOSY_KBN("SCV_HOSY_KBN"),
	TB_HOSY_CMT("TB_HOSY_CMT"),
	TJIK_KBN("TJIK_KBN"),
	SYADNO("SYADNO"),
	SYAK_KBN("SYAK_KBN"),
	TMPCN_ISDAY("TMPCN_ISDAY"),
	COLD_ISDAY("COLD_ISDAY"),
	CRN_SZONO("CRN_SZONO"),
	CRN_KKINO_1("CRN_KKINO_1"),
	CRN_KKINO_2("CRN_KKINO_2"),
	ACRN_SOTY_KBN("ACRN_SOTY_KBN"),
	CRN_SYDAY("CRN_SYDAY"),
	HGKS_KBN("HGKS_KBN"),
	UAGE_PNTCD("UAGE_PNTCD"),
	RECS_SY_PTNCD("RECS_SY_PTNCD"),
	KNSI_YTDAY("KNSI_YTDAY"),
	ZNKST_HBIHSI_YTYM("ZNKST_HBIHSI_YTYM"),
	SRKD_KBN("SRKD_KBN"),
	KIK_SIYMKTCD("KIK_SIYMKTCD"),
	UAGE_KGK("UAGE_KGK"),
	SVC_THK_KBN("SVC_THK_KBN"),
	HYK_INS_SY_CMT("HYK_INS_SY_CMT"),
	PRD_KOJOCD("PRD_KOJOCD"),
	MAKE_YM("MAKE_YM"),
	NCAR_UAGE_YMD("NCAR_UAGE_YMD"),
	OPE_SKK_CD_1("OPE_SKK_CD_1"),
	OPE_SKK_CD_2("OPE_SKK_CD_2"),
	OPE_SKK_CD_3("OPE_SKK_CD_3"),
	OPE_SKK_CD_4("OPE_SKK_CD_4"),
	OPE_SKK_CD_5("OPE_SKK_CD_5"),
	DBDKJ_KNR_SBT_1("DBDKJ_KNR_SBT_1"),
	DBDKJ_KNR_SBT_2("DBDKJ_KNR_SBT_2"),
	DBDKJ_KNR_SBT_3("DBDKJ_KNR_SBT_3"),
	DBDKJ_KNR_SBT_4("DBDKJ_KNR_SBT_4"),
	DBDKJ_KNR_SBT_5("DBDKJ_KNR_SBT_5"),
	CAR_CMT("CAR_CMT"),
	OLD_CMT_1("OLD_CMT_1"),
	OLD_CMT_2("OLD_CMT_2"),
	KOSMIC_SDFLG("KOSMIC_SDFLG"),
	LGC_FLG("LGC_FLG"),
	TRK_USERID("TRK_USERID"),
	TRK_PGMID("TRK_PGMID"),
	INP_DAYT("INP_DAYT"),
	SIS_KS_USERID("SIS_KS_USERID"),
	SIS_KS_PGMID("SIS_KS_PGMID"),
	LAST_UPD_DAYT("LAST_UPD_DAYT");

	private final String text;

	private _Syaryo(final String text) {
		this.text = text;
	}

	public String get(){
		return this.text;
	}
    }

}
